# Generated by Django 3.1.6 on 2021-02-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='context',
            new_name='content',
        ),
    ]
