# Generated by Django 3.1.6 on 2021-02-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_profileimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
