# Generated by Django 3.1.6 on 2021-02-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
