# Generated by Django 3.1.6 on 2021-02-21 08:00

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='myimage', verbose_name=django.contrib.auth.models.User),
        ),
    ]
